### ISSUE TITLE
convert to WSL2 option confusing

### ISSUE THREAD

**Issue by tobidelbruck** [DesktopECHO/xWSL#16]
README.md states that installation "could be converted to a WSL2 VM if required". This is confusing for newbies who just get WSL2 by default and install e.g. Ubuntu 18.04 and who don't know about WSL1/2, even if they are experienced windows/linux users.

Is xWSL a WSL2 VM like the stock Ubuntu VM?

Does xWSL constitute a *new* Ubuntu installation to WSL2?

Why should the xWSL be converted to a VM? Isn't it already a VM?  Or is xWSL a WSL1 installation? 

If I want to covert to WSL2 (not clear if needed), in "wsl --set-version [DistroName] 2", what is the DistroName?  Is this my existing Ubuntu 18 distro name? Is there a way to find it out?

As of now, I see this wsl list of distros:
wsl --list
Windows Subsystem for Linux Distributions:
xWSL (Default)
Ubuntu-20.04
Ubuntu-18.04

Sorry for newbie questions about xWSL.

**Comment by KushalSM** [comment]
When you use the script, it will automatically install wsl 1 version.. So you dont need to worry about it getting converted to wsl 2 automatically

**Comment by KushalSM** [comment]
Later you can convert it wsl 2 if you want

**Comment by KushalSM** [comment]
Also, you dont need to install ubuntu from the store... This script installs ubuntu for you with all the neccessary things for running a gui with sound

**Comment by DesktopECHO** [comment]
> README.md states that installation "could be converted to a WSL2 VM if required". This is confusing for newbies who just get WSL2 by default and install e.g. Ubuntu 18.04 and who don't know about WSL1/2, even if they are experienced windows/linux users.

I don't think you get WSL or WSL2 by default, it needs to be installed separately.  The script will detect if WSL support is installed and will do so if needed.

> 
> Is xWSL a WSL2 VM like the stock Ubuntu VM?

This is why MS should have named WSL2 something other than 'WSL2' - They are totally different approaches to running Linux in Windows.

- WSL1 is a Windows Subsystem (not unlike NTVDM back in the day) that runs Linux apps right alongside Win32 apps, so it's not really a virtual machine.  If you have Ubuntu running in WSL1 you can open Task Manager and see processes like 'bash' running right next to your Windows apps.  No hypervisor needed.

- WSL2 is a 'traditional' Virtual Machine that requires a hypervisor to run.  As a result it has its own virtual hardware, networking stack, storage, etc... and takes those resources away from Windows to run.  It's somewhat more capable than WSL1 because it's a 'real' Linux kernel, not a reimplementation of the Linux kernel ABI on top of the NT kernel.  From a technical point of view WSL1 is much more interesting than WSL2 as we've already had hypervisors around for many years.
> 
> Does xWSL constitute a _new_ Ubuntu installation to WSL2?

Yes, you don't need anything to install xWSL other than a fresh install of Windows.  It's fetches and installs the Ubuntu image directly from Microsoft's website.

> Why should the xWSL be converted to a VM? Isn't it already a VM? Or is xWSL a WSL1 installation?

It's just a matter of choice.  WSL1 can run on way older/less modern hardware.  One is not better than the other, just different.

> If I want to covert to WSL2 (not clear if needed), in "wsl --set-version [DistroName] 2", what is the DistroName? Is this my existing Ubuntu 18 distro name? Is there a way to find it out?

DistroName is the name you gave your distro when you ran the installer "xWSL" is the default name if you just hit enter.

> Sorry for newbie questions about xWSL.

All good!  It's easy to get mixed up if you've never worked with WSL before.  The MS naming scheme WSL1/WSL2 didn't help at all.

**Comment by DesktopECHO** [comment]
Added a Wiki Page for [Conversion to WSL2](https://github.com/DesktopECHO/xWSL/wiki/Convert-to-WSL2)
