### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by fabiovin70** [DesktopECHO/xWSL#33]
Hi,
I have tried a few times to install xWSL but I always get the message: "Access Denied".
I have tried always in powershell with administrative rights.
![immagine](https://user-images.githubusercontent.com/35801287/196891916-f96fb950-64b1-4b83-bdad-c6ad492c06d2.png)
![immagine](https://user-images.githubusercontent.com/35801287/196891950-d1559455-0e0e-4de5-a371-80071e2356c7.png)

This is my wsl version:
`PS C:\Users\fabio> wsl --version
Versione WSL: 0.70.0.0
Versione kernel: 5.15.68.1
Versione WSLg: 1.0.45
Versione MSRDC: 1.2.3575
Versione Direct3D: 1.606.4
Versione DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
versione Windows: 10.0.22621.674`

I'm on Windows 11 22H2 build 22621.674 all the available windows updates applied.

Thanks

**Comment by DesktopECHO** [comment]
It's working for me.  How much space do you have free on your C:\ drive?

**Comment by fabiovin70** [comment]
101 GB free

**Comment by DesktopECHO** [comment]
Hi there please empty the contents of your %TEMP% folder and re-run the script.  I just made a change a few minutes ago to get the image from GitHub instead of debian.org - The installer appears to be running well on a couple of test machines I tried.

![image](https://user-images.githubusercontent.com/33142753/197933530-4b9133f1-130d-4f14-ab35-3f8eb2eb9ec3.png)

**Comment by fabiovin70** [comment]
Hi,
I cancelled most of the files in the %temp% folder and re-run the script and everything has worked flawlessy.
Thank you!

**Comment by DesktopECHO** [comment]
Sweet!
