### ISSUE TITLE
error occured when opening rdp

### ISSUE THREAD

**Issue by KushalSM** [DesktopECHO/xWSL#9]
Remote desktop connecttion says that "an error occured while loading from file C:\Users\<username>\Ubuntu\rootfs\tmp\xWSL\xWSL.rdp

I dont know what to do

![Screenshot (106)](https://user-images.githubusercontent.com/64859307/86331566-e7ced780-bc66-11ea-917b-9517e044655b.png)

**Comment by KushalSM** [comment]
i hat to redo the process, so now it works but  no gui desktop visible

**Comment by KushalSM** [comment]
It works now like i explained above
thank you..

**Comment by DesktopECHO** [comment]
Hi @KushalSM, I appreciate the positive feedback.  
I think your earlier problems were due to DNS.  In some cases I've had to override nearby DNS servers in /etc/resolv.conf and replace with 8.8.8.8.  If you scroll up through the console output there may be additional clues. 

To stop automatic generation of /etc/resolv.conf add the following entry to /etc/wsl.conf:
 
 ```
 # [network]
 generateResolvConf = false
 ```
